chore: update test workflow

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -33,6 +33,32 @@ jobs:
       # This step runs `npm ci` to install any dependencies listed in your `package.json` file.
       - run: npm ci --legacy-peer-deps
       # This step runs the `build` script if there is one specified under the `scripts` key in your `package.json` file.
-      - run: npm run dev --if-present
+      name: Run npm run dev with Timeout
+      run: |
+        # Run the "npm run dev" command in the background
+        npm run dev &
+
+        # Get the process ID (PID) of the background process
+        dev_pid=$!
+
+        # Wait for a specific timeout (e.g., 60 seconds)
+        timeout=60
+        sleep $timeout
+
+        # Check if the process is still running
+        if ps -p $dev_pid > /dev/null; then
+          # Process is still running, terminate it
+          echo "The 'npm run dev' command is running for too long. Terminating..."
+          kill $dev_pid
+          exit 1
+        else
+          # Process has completed, check the exit status
+          if [ $? -eq 0 ]; then
+            echo "The 'npm run dev' command ran successfully."
+          else
+            echo "The 'npm run dev' command encountered an error."
+            exit 1
+          fi
+        fi
       # This step runs the `test` script that is specified under the `scripts` key in your `package.json` file.
       - run: npm run build --if-present
